const router = require('express').Router();
const PDFDocument = require('pdfkit');
const { pool } = require('../db');
const auth = require('../middleware/auth');

router.get('/pdf', auth, async (req, res) => {
  const { from, to, dairy_id, farmer_id, status } = req.query;
  const fromDate = from || new Date(Date.now() - 15 * 86400000).toISOString().split('T')[0];
  const toDate   = to   || new Date().toISOString().split('T')[0];

  if (fromDate > toDate) {
    return res.status(400).json({ error: 'From date cannot be after To date' });
  }

  try {
    const userRes = await pool.query('SELECT name, mobile FROM users WHERE id=$1', [req.userId]);
    const doctor  = userRes.rows[0];

    let conditions = ['v.user_id=$1'];
    let params = [req.userId];
    let idx = 2;
    conditions.push(`v.visit_date >= $${idx++}`); params.push(fromDate);
    conditions.push(`v.visit_date <= $${idx++}`); params.push(toDate);
    if (dairy_id)  { conditions.push(`f.dairy_id=$${idx++}`);       params.push(dairy_id); }
    if (farmer_id) { conditions.push(`v.farmer_id=$${idx++}`);      params.push(farmer_id); }
    if (status)    { conditions.push(`v.payment_status=$${idx++}`); params.push(status); }

    const visitsRes = await pool.query(
      `SELECT v.*, f.name AS farmer_name, f.village,
              d.name AS dairy_name, d.phone AS dairy_phone
       FROM visits v
       JOIN farmers f ON v.farmer_id = f.id
       LEFT JOIN dairies d ON f.dairy_id = d.id
       WHERE ${conditions.join(' AND ')}
       ORDER BY d.name NULLS LAST, f.name, v.visit_date`,
      params
    );
    const visits = visitsRes.rows;
    console.log(`[PDF] userId=${req.userId} from=${fromDate} to=${toDate} visits=${visits.length}`);

    const totalAmount   = visits.reduce((s, v) => s + parseFloat(v.amount || 0), 0);
    const paidAmount    = visits.filter(v => v.payment_status === 'PAID').reduce((s, v) => s + parseFloat(v.amount || 0), 0);
    const pendingAmount = totalAmount - paidAmount;

    // ── Page constants ────────────────────────────────────────────────────────
    const PAGE_W         = 595.28;
    const PAGE_H         = 841.89;
    const MARGIN         = 50;
    const FOOTER_H       = 36;
    const CONTENT_BOTTOM = PAGE_H - FOOTER_H - 10;
    const ROW_H          = 18;

    // ── Column layout (total 495 pts: x 50→545) ───────────────────────────────
    const COLS = [
      { label: 'Date',      x: 50,  w: 62 },
      { label: 'Farmer',    x: 112, w: 95 },
      { label: 'Village',   x: 207, w: 72 },
      { label: 'Animals',   x: 279, w: 42 },
      { label: 'Treatment', x: 321, w: 88 },
      { label: 'Amount',    x: 409, w: 55 },
      { label: 'Status',    x: 464, w: 81 }
    ];

    // ── Create PDF ────────────────────────────────────────────────────────────
    const doc = new PDFDocument({
      size: 'A4',
      margin: MARGIN,
      autoFirstPage: true,
      info: { Title: 'PashuLedger Report', Author: `Dr. ${doctor.name}` }
    });

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition',
      `attachment; filename="pashuledger-report-${fromDate}-to-${toDate}.pdf"`);
    doc.pipe(res);

    // ── Footer helper (NEVER call before content on same page) ────────────────
    // Uses doc.save/restore + absolute y — safe, no page-add side effects
    const footerLabel = `Generated by PashuLedger  |  Dr. ${doctor.name}  |  ${new Date().toLocaleDateString('en-IN')}  |  © NSN Technologies Pvt. Ltd., 2026`;
    const drawFooter = () => {
      const fy = PAGE_H - FOOTER_H;
      doc.save();
      doc.rect(0, fy, PAGE_W, FOOTER_H).fill('#1D9E75');
      doc.fillColor('white').fontSize(7.5).font('Helvetica')
         .text(footerLabel, MARGIN, fy + 13,
               { width: PAGE_W - MARGIN * 2, align: 'center', lineBreak: false });
      doc.restore();
    };

    // ── addNewPage: add page, draw footer on it immediately ──────────────────
    const addNewPage = () => {
      doc.addPage();
      drawFooter();
    };

    // ── Table helpers ─────────────────────────────────────────────────────────
    const drawTableHeader = (yPos) => {
      doc.rect(MARGIN, yPos, PAGE_W - MARGIN * 2, ROW_H).fill('#F1EFE8');
      COLS.forEach(c =>
        doc.fillColor('#444441').fontSize(8).font('Helvetica-Bold')
           .text(c.label, c.x, yPos + 5, { width: c.w, lineBreak: false })
      );
      return yPos + ROW_H;
    };

    const drawDataRow = (rowData, yPos, shade) => {
      if (shade) doc.rect(MARGIN, yPos, PAGE_W - MARGIN * 2, ROW_H).fill('#FAFAFA');
      rowData.forEach(({ val, col, color }) => {
        doc.save();
        doc.rect(col.x, yPos, col.w, ROW_H).clip();
        doc.fillColor(color || '#2C2C2A').fontSize(8).font('Helvetica')
           .text(String(val || ''), col.x, yPos + 5, { width: col.w, lineBreak: false });
        doc.restore();
      });
      return yPos + ROW_H;
    };

    // =========================================================================
    // PAGE 1 — draw header banner directly using doc.save/restore (no text wrap)
    // =========================================================================
    doc.save();
    doc.rect(0, 0, PAGE_W, 90).fill('#1D9E75');
    doc.fillColor('white').fontSize(22).font('Helvetica-Bold')
       .text('PashuLedger', MARGIN, 22, { lineBreak: false });
    doc.fontSize(10).font('Helvetica')
       .text('Veterinary Visit Tracker', MARGIN, 50, { lineBreak: false });
    doc.text(`Dr. ${doctor.name}  |  +91 ${doctor.mobile}`,
             PAGE_W - 250, 38, { width: 200, align: 'right', lineBreak: false });
    doc.rect(0, 90, PAGE_W, 28).fill('#085041');
    doc.fillColor('white').fontSize(10).font('Helvetica')
       .text(`Report Period: ${formatDate(fromDate)}  to  ${formatDate(toDate)}`,
             MARGIN, 98, { width: PAGE_W - MARGIN * 2, align: 'center', lineBreak: false });
    doc.restore();

    // Start content below the header — NO drawFooter() call here on page 1
    let y = 135;

    // ── Summary boxes ─────────────────────────────────────────────────────────
    const boxes = [
      { label: 'Total Visits', value: String(visits.length),            color: '#1D9E75' },
      { label: 'Total Amount', value: `Rs.${totalAmount.toFixed(0)}`,   color: '#185FA5' },
      { label: 'Collected',    value: `Rs.${paidAmount.toFixed(0)}`,    color: '#3B6D11' },
      { label: 'Pending',      value: `Rs.${pendingAmount.toFixed(0)}`, color: '#A32D2D' }
    ];
    const BOX_W = 115, BOX_H = 52, BOX_GAP = 10;
    const boxStartX = (PAGE_W - (boxes.length * BOX_W + (boxes.length - 1) * BOX_GAP)) / 2;

    boxes.forEach((b, i) => {
      const bx = boxStartX + i * (BOX_W + BOX_GAP);
      doc.roundedRect(bx, y, BOX_W, BOX_H, 5).fill(b.color);
      doc.fillColor('white').fontSize(16).font('Helvetica-Bold')
         .text(b.value, bx, y + 11, { width: BOX_W, align: 'center', lineBreak: false });
      doc.fontSize(8).font('Helvetica')
         .text(b.label, bx, y + 34, { width: BOX_W, align: 'center', lineBreak: false });
    });
    y += BOX_H + 18;

    // ── No visits ─────────────────────────────────────────────────────────────
    if (visits.length === 0) {
      doc.fillColor('#666666').fontSize(12).font('Helvetica')
         .text('No visits found for the selected period.',
               MARGIN, y + 20,
               { width: PAGE_W - MARGIN * 2, align: 'center', lineBreak: false });
      drawFooter(); // draw footer on this (only) page before ending
      doc.end();
      return;
    }

    // ── Group by dairy ────────────────────────────────────────────────────────
    const byDairy = {};
    visits.forEach(v => {
      const key = v.dairy_name || 'Independent';
      if (!byDairy[key]) byDairy[key] = [];
      byDairy[key].push(v);
    });

    // ── Render dairy sections ─────────────────────────────────────────────────
    const dairyEntries = Object.entries(byDairy);
    for (let di = 0; di < dairyEntries.length; di++) {
      const [dairyName, dVisits] = dairyEntries[di];

      // Need: dairy banner(22) + header row(18) + 1 data row(18) = 58 minimum
      if (y > CONTENT_BOTTOM - 58) {
        // Before leaving this page, draw its footer
        drawFooter();
        addNewPage();
        y = MARGIN;
      }

      // Dairy section banner
      doc.rect(MARGIN, y, PAGE_W - MARGIN * 2, 22).fill('#E1F5EE');
      doc.fillColor('#085041').fontSize(10).font('Helvetica-Bold')
         .text(`Dairy: ${dairyName}`, 58, y + 6, { lineBreak: false });
      const dTotal = dVisits.reduce((s, v) => s + parseFloat(v.amount || 0), 0);
      doc.fillColor('#085041').fontSize(9).font('Helvetica-Bold')
         .text(`Total: Rs.${dTotal.toFixed(0)}`,
               PAGE_W - 160, y + 6, { width: 100, align: 'right', lineBreak: false });
      y += 28;

      y = drawTableHeader(y);

      for (let ri = 0; ri < dVisits.length; ri++) {
        const v = dVisits[ri];

        if (y > CONTENT_BOTTOM - ROW_H) {
          drawFooter();
          addNewPage();
          y = MARGIN;
          y = drawTableHeader(y);
        }

        const statusLabel = v.payment_status === 'PAID' ? 'PAID' : 'PENDING';
        const statusColor = v.payment_status === 'PAID' ? '#3B6D11' : '#854F0B';

        y = drawDataRow([
          { val: formatDate(v.visit_date),                        col: COLS[0] },
          { val: v.farmer_name,                                   col: COLS[1] },
          { val: v.village || '\u2014',                           col: COLS[2] },
          { val: v.animals_count,                                 col: COLS[3] },
          { val: v.treatment,                                     col: COLS[4] },
          { val: `Rs.${parseFloat(v.amount || 0).toFixed(0)}`,   col: COLS[5] },
          { val: statusLabel, color: statusColor,                 col: COLS[6] }
        ], y, ri % 2 === 0);
      }

      y += 12;
    }

    // Draw footer on the final page
    drawFooter();

    doc.end();

  } catch (err) {
    console.error('[PDF] Error:', err);
    if (!res.headersSent) {
      res.status(500).json({ error: 'Could not generate PDF' });
    }
  }
});

function formatDate(d) {
  if (!d) return '';
  return new Date(d).toLocaleDateString('en-IN', {
    day: '2-digit', month: 'short', year: 'numeric'
  });
}

module.exports = router;